### ISSUE TITLE
Hroku Suspention

### ISSUE THREAD

**Issue by NEOIR** [odysseusmax/tg-index#18]
Hi.

in new version when deploy on heroku account suspention, Why ?

with old version not any problem :

heroku suspention mesage is:
--------------------------------------------------------------------------------------------------------------------------
This is a notice to inform you that your Heroku account tgi@ravali.tk has been suspended.

Reason for suspension: violation of the Heroku Acceptable Use Policy.

**If you believe this account has been suspended in error, please email suspended-account@heroku.com.**

The Heroku Team
https://heroku.com 
----------------------------------------------------------------------------------------------------------------------------

**Comment by pseudokawaii** [comment]
I'm having the same issue. My main account got ssuspended, then i created 3 more accounts and got every one of them suspended trying to deploy this repo.

**Comment by NEOIR** [comment]
:pensive:

**Comment by NEOIR** [comment]
fixed ? Or Not ?

**Comment by pseudokawaii** [comment]
> fixed ? Or Not ?

not yet.

**Comment by ravidkumar** [comment]
You got suspended once and decided to waste 3 more accounts.. 😂😂

**Comment by pseudokawaii** [comment]
> You got suspended once and decided to waste 3 more accounts.. 😂😂

How 's that a waste? Heroku's not picky about email providers so you can create any number of account you want using temporary emails. I just wanted to confirm why was i suspended and i really did find out reason after getting banned 4 times, do you want to know why they ban this repo?

**Comment by NEOIR** [comment]
@pseudokawaii 
You Can Contact With Heroku Support Center

**Comment by NEOIR** [comment]
Or Please Check to Deployment on Blow Hosting Package With Python APP Runner

https://docs.planethoster.com/guide/panneaux-de-controle/world-panel/world-panel-infos-additionnelles/langages-python

**Comment by Deepandx** [comment]
solution found or not guys pls help

**Comment by pseudokawaii** [comment]
@Deepandx use https://repl.it, heroku doesn't allow any scrapper script now. since this code is pure Telegram scrapping code, heroku blocks it.

**Comment by NEOIR** [comment]
@pseudokawaii How to Deploy on repl.it ?

**Comment by pseudokawaii** [comment]
@NEOIR Here's how ~

1. Open your https://repl.it dashboard.

2. add a new repl.

3. choose "import from github" and copy paste the link of this repo.

4. start the repl, it'll clone the github repo and detect what type of project is it.

5. it'll ask you to set a 'run command', use `pip3 install -r requirements.txt && python3 -m app` as the the 'run command' and save it. repl.it will set up the project for python.

6. don't run the project yet. create a new file in the root directory named `.env` and put all your configurations (like `API_ID`, `API_HASH` & `INDEX_SETTINGS`) in the `.env` file using the informations on the README page. DON'T USE ANY SPACE BETWEEN KEYS AND VALUES OR UNNECESSARY CHARACTERS IN THE  .ENV FILE AND WRAP ALL THE VALUES WITH SINGLE/DOUBLE QUOTES OR YOU'LL GET A KEYERROR)

7. finally, finish editing the `.env` file and run/start your repl using the big button.

8. If everything goes well, you should see the pip module installing the requirements and then starting the repl. It will open a web window and you should see your telegram index channels.

**Comment by landjie** [comment]
> @NEOIR这是〜
> 
> 1. 打开您的https://repl.it仪表板。
> 2. 添加一个新的代表。
> 3. 选择“从github导入”，然后复制粘贴此仓库的链接。
> 4. 启动repl，它将克隆github repo并检测它是什么类型的项目。
> 5. 它会要求您设置一个“运行命令”，`pip3 install -r requirements.txt && python3 -m app`用作“运行命令”并保存。repl.it将为python建立项目。
> 6. 不要运行该项目。中创建一个名为根目录下的新文件`.env`，并把所有的配置（如`API_ID`，`API_HASH`＆`INDEX_SETTINGS`）中`.env`使用的README页面上的信息文件。请勿在.ENV文件中使用键和值或不必要的字符之间的任何空格，并用单/双引号将所有值包起来，否则会出现键错误）
> 7. 最后，完成`.env`文件的编辑并使用大按钮运行/启动您的副本。
> 8. 如果一切顺利，您应该看到pip模块安装了需求，然后启动了repl。它将打开一个网络窗口，您应该看到电报索引频道。

**Comment by landjie** [comment]
> @NEOIR这是〜
> 
> 1. 打开您的https://repl.it仪表板。
> 2. 添加一个新的代表。
> 3. 选择“从github导入”，然后复制粘贴此仓库的链接。
> 4. 启动repl，它将克隆github repo并检测它是什么类型的项目。
> 5. 它会要求您设置一个“运行命令”，`pip3 install -r requirements.txt && python3 -m app`用作“运行命令”并保存。repl.it将为python建立项目。
> 6. 不要运行该项目。中创建一个名为根目录下的新文件`.env`，并把所有的配置（如`API_ID`，`API_HASH`＆`INDEX_SETTINGS`）中`.env`使用的README页面上的信息文件。请勿在.ENV文件中使用键和值或不必要的字符之间的任何空格，并用单/双引号将所有值包起来，否则会出现键错误）
> 7. 最后，完成`.env`文件的编辑并使用大按钮运行/启动您的副本。
> 8. 如果一切顺利，您应该看到pip模块安装了需求，然后启动了repl。它将打开一个网络窗口，您应该看到电报索引频道。

After the deployment is successful, close the website and the reply will automatically stop running.

**Comment by landjie** [comment]
> @NEOIR Here's how ~
> 
> 1. Open your https://repl.it dashboard.
> 2. add a new repl.
> 3. choose "import from github" and copy paste the link of this repo.
> 4. start the repl, it'll clone the github repo and detect what type of project is it.
> 5. it'll ask you to set a 'run command', use `pip3 install -r requirements.txt && python3 -m app` as the the 'run command' and save it. repl.it will set up the project for python.
> 6. don't run the project yet. create a new file in the root directory named `.env` and put all your configurations (like `API_ID`, `API_HASH` & `INDEX_SETTINGS`) in the `.env` file using the informations on the README page. DON'T USE ANY SPACE BETWEEN KEYS AND VALUES OR UNNECESSARY CHARACTERS IN THE  .ENV FILE AND WRAP ALL THE VALUES WITH SINGLE/DOUBLE QUOTES OR YOU'LL GET A KEYERROR)
> 7. finally, finish editing the `.env` file and run/start your repl using the big button.
> 8. If everything goes well, you should see the pip module installing the requirements and then starting the repl. It will open a web window and you should see your telegram index channels.

After the deployment is successful, close the website and the reply will automatically stop running.

**Comment by pseudokawaii** [comment]
@landjie that's the limitation of repl.it, it throws random errors after the first deployment.
