### ISSUE TITLE
File Download Dropped

### ISSUE THREAD

**Issue by stepin104678** [odysseusmax/tg-index#2]
File download gets cancelled at the end of the download. 
@odysseusmax consider this issue.

**Comment by odysseusmax** [comment]
Provide logs

**Comment by stepin104678** [comment]
[log_file.txt](https://github.com/odysseusmax/tg-index/files/5073397/log_file.txt)

Attached log file.
Download goes smooth till the end of the download. It restarts the download or showing error download interepted.

**Comment by odysseusmax** [comment]
> [log_file.txt](https://github.com/odysseusmax/tg-index/files/5073397/log_file.txt)
> 
> Attached log file.
> Download goes smooth till the end of the download. It restarts the download or showing error download interrupted.

please enable DEBUG and send logs

**Comment by stepin104678** [comment]
After Updating, it works fine.
Download doesn't interrupt.

**Comment by Herokubot123** [comment]
bro i have issue if iam downloading a file and turn offing data then turn on it shows no file.. 

2020-08-17T03:37:49.077995+00:00 heroku[router]: sock=client at=warning code=H27 desc="Client Request Interrupted" method=GET path="/qKaAujbbQrbDm9/59424/download" request_id=ac381c4a-9c1a-4eeb-a2b0-923acc1750f3 fwd="157.46.216.37" dyno=web.1 connect=1ms service=69145ms status=499 bytes= protocol=https

2020-08-17T03:37:49.078056+00:00 app[web.1]: DEBUG:app.telegram:Part 226/779 (total 779) served!

2020-08-17T03:37:49.082365+00:00 app[web.1]: DEBUG:app.telegram:file serve interrupted

**Comment by odysseusmax** [comment]
> bro, I have an issue if I am downloading a file and turning off data then turn on it shows no file..
> 
> 2020-08-17T03:37:49.077995+00:00 heroku[router]: sock=client at=warning code=H27 desc="Client Request Interrupted" method=GET path="/qKaAujbbQrbDm9/59424/download" request_id=ac381c4a-9c1a-4eeb-a2b0-923acc1750f3 fwd="157.46.216.37" dyno=web.1 connect=1ms service=69145ms status=499 bytes= protocol=https
> 
> 2020-08-17T03:37:49.078056+00:00 app[web.1]: DEBUG:app.telegram:Part 226/779 (total 779) served!
> 
> 2020-08-17T03:37:49.082365+00:00 app[web.1]: DEBUG:app.telegram:file serve interrupted

thats not the issue with this app.
