### ISSUE TITLE
USERNAME is a internal env variable in windows 

### ISSUE THREAD

**Issue by rayanfer32** [odysseusmax/tg-index#28]
`USERNAME` cannot be used in .env to set `USERNAME` for authentication in the tg-index ... the system picks the system username by default.

**Comment by viper-adnan** [comment]
Change the `USERNAME` to `USER` or something here...
https://github.com/odysseusmax/tg-index/blob/504a1785d12771004a05165d2d4be2fc81c6f8bc/app/config.py#L49
