### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by zoredeaxx** [odysseusmax/tg-index#51]
Unfortunately, the code seems to have stopped working on replit. please look into the matter and update the repo.

**Comment by odysseusmax** [comment]
I tried, it was working. Please elaborate the issue.

**Comment by zoredeaxx** [comment]
The code executes on the replit website flawlessly, however, the web inferface fails to load. Till yesterday it was working perfectly fine. May I know what could be the issue....

**Comment by minicrack56** [comment]
indeed, the web interface only shows a white background

**Comment by odysseusmax** [comment]
> 
> 
> The code executes on the replit website flawlessly, however, the web inferface fails to load. Till yesterday it was working perfectly fine. May I know what could be the issue....

There was some update to aiohttp which caused some issues in the app, the latest changes should have fixed the issue.

**Comment by zoredeaxx** [comment]
> > The code executes on the replit website flawlessly, however, the web inferface fails to load. Till yesterday it was working perfectly fine. May I know what could be the issue....
> 
> There was some update to aiohttp which caused some issues in the app, the latest changes should have fixed the issue.

Really greatful to you for the fix.... It's working again. Thanks
