### ISSUE TITLE
Session String Error

### ISSUE THREAD

**Issue by zoredeaxx** [odysseusmax/tg-index#59]

**Comment by zoredeaxx** [comment]
1. Off late a strange issue is being observed on replit. Random errors are being shown for the generated session string and the session ends abrubtly, logging out the client after couple of days. The issue never appeared earlier wherein the login continued even for months. The issue remains with different telethon versions. 
2. Is anyone else facing the issue.
3. Any solution for the same is highly appreciable.

**Comment by rayanfer32** [comment]
There must be a way to turn off session string expiration when two
applications are detected.
